### ISSUE TITLE
Hanging on class_4706

### ISSUE THREAD

**Issue by Runemoro** [FabricMC/Enigma#182]
Enigma hangs on `class_4706`, yet the class is decompiled correctly by Procyon when exporting source, meaning it's an Enigma bug, not a Procyon bug.

**Comment by 2xsaiko** [comment]
That's actually a crash while remapping:

```
java.lang.IllegalArgumentException: don't use with generic types or templates: T
	at cuchaz.enigma.translation.representation.TypeDescriptor.<init>(TypeDescriptor.java:36)
	at cuchaz.enigma.translation.representation.TypeDescriptor.getArrayType(TypeDescriptor.java:172)
	at cuchaz.enigma.translation.representation.TypeDescriptor.containsType(TypeDescriptor.java:176)
	at cuchaz.enigma.translation.representation.TypeDescriptor.remap(TypeDescriptor.java:195)
	at cuchaz.enigma.translation.representation.TypeDescriptor.translate(TypeDescriptor.java:232)
	at cuchaz.enigma.translation.MappingTranslator.translate(MappingTranslator.java:22)
	at cuchaz.enigma.translation.representation.entry.ClassEntry.translate(ClassEntry.java:67)
	at cuchaz.enigma.translation.representation.entry.ClassEntry.translate(ClassEntry.java:26)
	at cuchaz.enigma.translation.representation.entry.ParentedEntry.translate(ParentedEntry.java:66)
	at cuchaz.enigma.translation.representation.entry.ParentedEntry.translate(ParentedEntry.java:23)
	at cuchaz.enigma.translation.MappingTranslator.translate(MappingTranslator.java:22)
	at cuchaz.enigma.translation.representation.entry.ParentedEntry.translate(ParentedEntry.java:68)
	at cuchaz.enigma.translation.representation.entry.ParentedEntry.translate(ParentedEntry.java:23)
	at cuchaz.enigma.translation.MappingTranslator.translate(MappingTranslator.java:22)
	at cuchaz.enigma.source.DecompiledClassSource.remapToken(DecompiledClassSource.java:51)
	at cuchaz.enigma.source.DecompiledClassSource.lambda$remapSource$0(DecompiledClassSource.java:43)
	at cuchaz.enigma.source.SourceRemapper.remap(SourceRemapper.java:23)
	at cuchaz.enigma.source.DecompiledClassSource.remapSource(DecompiledClassSource.java:43)
	at cuchaz.enigma.classhandle.ClassHandleProvider$Entry.lambda$continueMapSource$19(ClassHandleProvider.java:290)
	at cuchaz.enigma.utils.Result.andThen(Result.java:82)
	at cuchaz.enigma.classhandle.ClassHandleProvider$Entry.lambda$continueMapSource$23(ClassHandleProvider.java:288)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire$$$capture(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by 2xsaiko** [comment]
Pushed 50d4fc8 which at least makes that crash visible, not sure if I can fix it for real.
