### ISSUE TITLE
CFR issues

### ISSUE THREAD

**Issue by Runemoro** [FabricMC/Enigma#195]
- Imports are not removed, and not remapped correctly
 - Lambdas aren't decompiling properly?
 - Decompiler choice menu should have checkboxes
 - particlefactory and class_4952 doesn't decompile anymore with procyon
 - Parameter indices are wrong?

**Comment by Runemoro** [comment]
```
java.lang.NullPointerException
    at cuchaz.enigma.source.cfr.EnigmaDumper.getMethodEntry(EnigmaDumper.java:85)
    at cuchaz.enigma.source.cfr.EnigmaDumper.methodName(EnigmaDumper.java:170)
    at org.benf.cfr.reader.bytecode.analysis.parse.expression.LambdaExpressionNewArray.dumpInner(LambdaExpressionNewArray.java:31)
    at org.benf.cfr.reader.bytecode.analysis.parse.expression.AbstractExpression.dumpWithOuterPrecedence(AbstractExpression.java:124)
    at org.benf.cfr.reader.bytecode.analysis.parse.expression.AbstractExpression.dump(AbstractExpression.java:80)
    at org.benf.cfr.reader.bytecode.analysis.types.MethodPrototype.dumpAppropriatelyCastedArgumentString(MethodPrototype.java:556)
    at org.benf.cfr.reader.bytecode.analysis.parse.expression.MemberFunctionInvokation.dumpInner(MemberFunctionInvokation.java:62)
    at org.benf.cfr.reader.bytecode.analysis.parse.expression.AbstractExpression.dumpWithOuterPrecedence(AbstractExpression.java:124)
    at org.benf.cfr.reader.bytecode.analysis.parse.expression.CastExpression.dumpInner(CastExpression.java:95)
    at org.benf.cfr.reader.bytecode.analysis.parse.expression.AbstractExpression.dumpWithOuterPrecedence(AbstractExpression.java:124)
    at org.benf.cfr.reader.bytecode.analysis.parse.expression.AbstractExpression.dump(AbstractExpression.java:80)
    at cuchaz.enigma.source.cfr.EnigmaDumper.dump(EnigmaDumper.java:312)
```

**Comment by liach** [comment]
Cfr maps outer class correctly but not inner classes.
