### ISSUE TITLE
NullPointer Exception when exporting source

### ISSUE THREAD

**Issue by Inky-developer** [FabricMC/Enigma#202]
Importing a jar (minecraft 1.15.2) and the client mappings works fine, but exporting to source crashes unfortunately. 
This is the error message:
`
java.lang.Error: java.lang.NullPointerException
        at cuchaz.enigma.gui.dialog.ProgressDialog.lambda$runOffThread$0(ProgressDialog.java:71)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source)
        at java.util.concurrent.ForkJoinTask.reportException(Unknown Source)
        at java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
        at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.collect(Unknown Source)
        at cuchaz.enigma.EnigmaProject$JarExport.decompile(EnigmaProject.java:216)
        at cuchaz.enigma.gui.GuiController.lambda$exportSource$5(GuiController.java:193)
        at cuchaz.enigma.gui.dialog.ProgressDialog.lambda$runOffThread$0(ProgressDialog.java:67)
        ... 1 more
Caused by: java.lang.NullPointerException
        at cuchaz.enigma.source.cfr.EnigmaDumper.getMethodEntry(EnigmaDumper.java:85)
        at cuchaz.enigma.source.cfr.EnigmaDumper.methodName(EnigmaDumper.java:170)
        at org.benf.cfr.reader.bytecode.analysis.parse.expression.LambdaExpressionNewArray.dumpInner(LambdaExpressionNewArray.java:31)
        at org.benf.cfr.reader.bytecode.analysis.parse.expression.AbstractExpression.dumpWithOuterPrecedence(AbstractExpression.java:124)
        at org.benf.cfr.reader.bytecode.analysis.parse.expression.AbstractExpression.dump(AbstractExpression.java:80)
        at org.benf.cfr.reader.bytecode.analysis.types.MethodPrototype.dumpAppropriatelyCastedArgumentString(MethodPrototype.java:556)
        at org.benf.cfr.reader.bytecode.analysis.parse.expression.MemberFunctionInvokation.dumpInner(MemberFunctionInvokation.java:62)
        at org.benf.cfr.reader.bytecode.analysis.parse.expression.AbstractExpression.dumpWithOuterPrecedence(AbstractExpression.java:124)
        at org.benf.cfr.reader.bytecode.analysis.parse.expression.CastExpression.dumpInner(CastExpression.java:95)
        at org.benf.cfr.reader.bytecode.analysis.parse.expression.AbstractExpression.dumpWithOuterPrecedence(AbstractExpression.java:124)
        at org.benf.cfr.reader.bytecode.analysis.parse.expression.AbstractExpression.dump(AbstractExpression.java:80)
        at cuchaz.enigma.source.cfr.EnigmaDumper.dump(EnigmaDumper.java:312)
        at org.benf.cfr.reader.bytecode.analysis.parse.expression.StaticFunctionInvokation.dumpInner(StaticFunctionInvokation.java:116)
        at org.benf.cfr.reader.bytecode.analysis.parse.expression.AbstractExpression.dumpWithOuterPrecedence(AbstractExpression.java:124)
        at org.benf.cfr.reader.bytecode.analysis.parse.expression.AbstractExpression.dump(AbstractExpression.java:80)
        at cuchaz.enigma.source.cfr.EnigmaDumper.dump(EnigmaDumper.java:312)
        at org.benf.cfr.reader.bytecode.analysis.structured.statement.StructuredAssignment.dump(StructuredAssignment.java:61)
        at org.benf.cfr.reader.bytecode.analysis.opgraph.Op04StructuredStatement.dump(Op04StructuredStatement.java:213)
        at org.benf.cfr.reader.bytecode.analysis.structured.statement.Block.dump(Block.java:557)
        at org.benf.cfr.reader.bytecode.analysis.structured.expression.StructuredStatementExpression.dumpInner(StructuredStatementExpression.java:86)
        at org.benf.cfr.reader.bytecode.analysis.parse.expression.AbstractExpression.dumpWithOuterPrecedence(AbstractExpression.java:124)
        at org.benf.cfr.reader.bytecode.analysis.parse.expression.AbstractExpression.dump(AbstractExpression.java:80)
        at cuchaz.enigma.source.cfr.EnigmaDumper.dump(EnigmaDumper.java:312)
        at org.benf.cfr.reader.bytecode.analysis.parse.expression.LambdaExpression.dumpInner(LambdaExpression.java:115)
        at org.benf.cfr.reader.bytecode.analysis.parse.expression.AbstractExpression.dumpWithOuterPrecedence(AbstractExpression.java:124)
        at org.benf.cfr.reader.bytecode.analysis.parse.expression.AbstractExpression.dump(AbstractExpression.java:80)
        at cuchaz.enigma.source.cfr.EnigmaDumper.dump(EnigmaDumper.java:312)
        at org.benf.cfr.reader.bytecode.analysis.structured.statement.StructuredExpressionStatement.dump(StructuredExpressionStatement.java:27)
        at org.benf.cfr.reader.bytecode.analysis.structured.expression.StructuredStatementExpression.dumpInner(StructuredStatementExpression.java:86)
        at org.benf.cfr.reader.bytecode.analysis.parse.expression.AbstractExpression.dumpWithOuterPrecedence(AbstractExpression.java:124)
        at org.benf.cfr.reader.bytecode.analysis.parse.expression.AbstractExpression.dump(AbstractExpression.java:80)
        at cuchaz.enigma.source.cfr.EnigmaDumper.dump(EnigmaDumper.java:312)
        at org.benf.cfr.reader.bytecode.analysis.parse.expression.LambdaExpression.dumpInner(LambdaExpression.java:115)
        at org.benf.cfr.reader.bytecode.analysis.parse.expression.AbstractExpression.dumpWithOuterPrecedence(AbstractExpression.java:124)
        at org.benf.cfr.reader.bytecode.analysis.parse.expression.AbstractExpression.dump(AbstractExpression.java:80)
        at org.benf.cfr.reader.bytecode.analysis.types.MethodPrototype.dumpAppropriatelyCastedArgumentString(MethodPrototype.java:556)
        at org.benf.cfr.reader.bytecode.analysis.parse.expression.MemberFunctionInvokation.dumpInner(MemberFunctionInvokation.java:62)
        at org.benf.cfr.reader.bytecode.analysis.parse.expression.AbstractExpression.dumpWithOuterPrecedence(AbstractExpression.java:124)
        at org.benf.cfr.reader.bytecode.analysis.parse.expression.AbstractExpression.dump(AbstractExpression.java:80)
        at cuchaz.enigma.source.cfr.EnigmaDumper.dump(EnigmaDumper.java:312)
        at org.benf.cfr.reader.bytecode.analysis.structured.statement.StructuredReturn.dump(StructuredReturn.java:52)
        at org.benf.cfr.reader.bytecode.analysis.opgraph.Op04StructuredStatement.dump(Op04StructuredStatement.java:213)
        at org.benf.cfr.reader.bytecode.analysis.structured.statement.Block.dump(Block.java:557)
        at org.benf.cfr.reader.bytecode.analysis.opgraph.Op04StructuredStatement.dump(Op04StructuredStatement.java:213)
        at org.benf.cfr.reader.entities.attributes.AttributeCode.dump(AttributeCode.java:135)
        at cuchaz.enigma.source.cfr.EnigmaDumper.dump(EnigmaDumper.java:312)
        at org.benf.cfr.reader.entities.Method.dump(Method.java:571)
        at org.benf.cfr.reader.entities.classfilehelpers.AbstractClassFileDumper.dumpMethods(AbstractClassFileDumper.java:188)
        at org.benf.cfr.reader.entities.classfilehelpers.ClassFileDumperNormal.dump(ClassFileDumperNormal.java:77)
        at org.benf.cfr.reader.entities.ClassFile.dump(ClassFile.java:1137)
        at cuchaz.enigma.source.cfr.CfrSource.<init>(CfrSource.java:19)
        at cuchaz.enigma.source.cfr.CfrDecompiler.getSource(CfrDecompiler.java:106)
        at cuchaz.enigma.EnigmaProject$JarExport.decompileClass(EnigmaProject.java:222)
        at cuchaz.enigma.EnigmaProject$JarExport.lambda$decompile$1(EnigmaProject.java:213)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source)
        at java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source)
        at java.util.stream.AbstractTask.compute(Unknown Source)
        at java.util.concurrent.CountedCompleter.exec(Unknown Source)
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
`

**Comment by Inky-developer** [comment]
I don't know if this helps but I the latest working version seems to be 0.14.3.149
