### ISSUE TITLE
Tiny v1 reader has dependency on Darcula LaF

### ISSUE THREAD

**Issue by Juuxel** [FabricMC/Enigma#234]
Not sure whether this is intended. It happens when the reader tries to display a localized progress message, which initializes `Config`, which in turn contains a reference to the Darcula look and feel.

Relevant stacktrace snippet:
```
Caused by: java.lang.NoClassDefFoundError: com/bulenkov/darcula/DarculaLaf
	at cuchaz.enigma.config.Config.<init>(Config.java:189)
	at cuchaz.enigma.config.Config.<clinit>(Config.java:159)
	at cuchaz.enigma.utils.I18n.<clinit>(I18n.java:29)
	at cuchaz.enigma.translation.mapping.serde.TinyMappingsReader.read(TinyMappingsReader.java:36)
	at cuchaz.enigma.translation.mapping.serde.TinyMappingsReader.read(TinyMappingsReader.java:29)
	at cuchaz.enigma.command.MappingCommandsUtil.read(MappingCommandsUtil.java:89)
	at cuchaz.enigma.command.ConvertMappingsCommand.run(ConvertMappingsCommand.java:33)
```

**Comment by Runemoro** [comment]
Also fixed by #242.
