### ISSUE TITLE
Could not run cli

### ISSUE THREAD

**Issue by MrIvanPlays** [FabricMC/Enigma#271]
Build: https://maven.fabricmc.net/cuchaz/enigma-cli/0.19%2Bbuild.193/
```$ java -cp enigma-cli.jar cuchaz.enigma.command.Main
HOTSWAP AGENT: 20:43:25.569 INFO (org.hotswap.agent.HotswapAgent) - Loading Hotswap agent {1.4.0} - unlimited runtime class redefinition.
HOTSWAP AGENT: 20:43:25.865 INFO (org.hotswap.agent.config.PluginRegistry) - Discovered plugins: [JdkPlugin, Hotswapper, WatchResources, ClassInitPlugin, AnonymousClassPatch, Hibernate, Hibernate3JPA, Hibernate3, Spring, Jersey1, Jersey2, Jetty, Tomcat, ZK, Logback, Log4j2, MyFaces, Mojarra, Omnifaces, ELResolver, WildFlyELResolver, OsgiEquinox, Owb, Proxy, WebObjects, Weld, JBossModules, ResteasyRegistry, Deltaspike, GlassFish, Vaadin, Wicket, CxfJAXRS, FreeMarker, Undertow, MyBatis]
Starting HotswapAgent 'C:\Program Files\AdoptOpenJDK\jdk-11.0.6.10-hotspot\lib\hotswap\hotswap-agent.jar'
Exception in thread "main" java.lang.NoClassDefFoundError: cuchaz/enigma/ProgressListener
        at cuchaz.enigma.command.Main.<clinit>(Main.java:83)
Caused by: java.lang.ClassNotFoundException: cuchaz.enigma.ProgressListener
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 1 more
```

Perhaps some dependency shading issue?

**Comment by 2xsaiko** [comment]
Looks like it doesn't include the other modules which are necessary for it to run.

**Comment by 2xsaiko** [comment]
Fixed in 9089a63.

Try the -all jar in https://maven.fabricmc.net/cuchaz/enigma-cli/0.19%2Bbuild.194/!

**Comment by MrIvanPlays** [comment]
I got this
```java.lang.RuntimeException: Unknown token 'COM.MOJANG.MATH.MATRIX3F'
        at cuchaz.enigma.translation.mapping.serde.enigma.EnigmaMappingsReader.parseLine(EnigmaMappingsReader.java:176)
        at cuchaz.enigma.translation.mapping.serde.enigma.EnigmaMappingsReader.readFile(EnigmaMappingsReader.java:96)
        at cuchaz.enigma.translation.mapping.serde.enigma.EnigmaMappingsReader$1.read(EnigmaMappingsReader.java:40)
        at cuchaz.enigma.translation.mapping.serde.MappingFormat.read(MappingFormat.java:53)
        at cuchaz.enigma.command.Command.openProject(Command.java:43)
        at cuchaz.enigma.command.DeobfuscateCommand.run(DeobfuscateCommand.java:30)
        at cuchaz.enigma.command.Main.main(Main.java:43)
cuchaz.enigma.translation.mapping.serde.MappingParseException: Line 0: java.lang.RuntimeException: Unknown token 'COM.MOJANG.MATH.MATRIX3F' in file D:\Minecraft server\server.txt
Enigma - 0.19+build.194```
Now it looks like it can't recognize mapping types, could you please add argument to specify what type are they?

**Comment by 2xsaiko** [comment]
Please make a seperate issue for that.
