### ISSUE TITLE
Exported jar not runnable

### ISSUE THREAD

**Issue by balaramsudip** [FabricMC/Enigma#307]
Basically, I ran the exported jar from the enigma deobfuscator and got a large error message : 

> Exception in thread "main" java.lang.ClassFormatError: Duplicate method name "serialize" with signature "(Lcom.google.gson.JsonObject;Lnet.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer;Lcom.google.gson.JsonSerializationContext;)V" in class file net/minecraft/world/level/storage/loot/entries/LootPoolEntryContainer$Serializer
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at net.minecraft.world.level.storage.loot.entries.LootPoolEntries.<clinit>(SourceFile:9)
	at net.minecraft.core.Registry.lambda$static$27(SourceFile:183)
	at net.minecraft.core.Registry.lambda$static$46(SourceFile:246)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at net.minecraft.core.Registry.<clinit>(SourceFile:245)
	at net.minecraft.server.Bootstrap.bootStrap(SourceFile:42)
	at net.minecraft.client.main.Main.main(SourceFile:137)

**Comment by balaramsudip** [comment]
The deobfuscator doesn't really work when it comes to exporting jar files. The field names are still obfuscated if they are called, but not obfuscated on declaration and initialization. This obviously would lead to a NoSuchFieldError if the above issue was fixed.

**Comment by Runemoro** [comment]
This is using mojmaps?

**Comment by NebelNidas** [comment]
The Fabric toolchain quite prominently states that it's not intended for recompilation, so I guess this is a non-issue. On a separate note, wouldn't it be best to remove Enigma's "Export source" / "Export JAR" options entirely? Because we already have Tiny Remapper for that, a tool specifically built for this use case and hence far more powerful. Simultaneously it would help cleaning up Enigma's codebase
