### ISSUE TITLE
java.lang.IllegalArgumentException: Unable to parse method descriptor: (/)L/;

### ISSUE THREAD

**Issue by toqzd0** [FabricMC/Enigma#455]
at cuchaz.enigma.translation.representation.MethodDescriptor.<init>(MethodDescriptor.java:55)
	at cuchaz.enigma.translation.representation.entry.MethodDefEntry.parse(MethodDefEntry.java:43)
	at cuchaz.enigma.analysis.index.IndexClassVisitor.visitMethod(IndexClassVisitor.java:36)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:645)
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:451)
	at cuchaz.enigma.analysis.index.JarIndex.indexJar(JarIndex.java:68)
	at cuchaz.enigma.Enigma.openJar(Enigma.java:65)
	at cuchaz.enigma.gui.GuiController.lambda$openJar$1(GuiController.java:105)
	at cuchaz.enigma.gui.dialog.ProgressDialog.lambda$runOffThread$1(ProgressDialog.java:97)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.IllegalArgumentException: don't know how to parse: /)L/;
	at cuchaz.enigma.translation.representation.TypeDescriptor.parseFirst(TypeDescriptor.java:82)
	at cuchaz.enigma.translation.representation.MethodDescriptor.<init>(MethodDescriptor.java:48)
	... 15 more

**Comment by modmuss50** [comment]
Some more info on how to reproduce this would be useful.

What Engima version, what input jar? How did you get to this?

**Comment by toqzd0** [comment]
> Некоторая дополнительная информация о том, как воспроизвести это, была бы полезна.
> 
> Какая версия Engima, какая входная банка? Как вы к этому пришли?

1. last version
2. i draw to enigma my obfuscated file and enigma retrieved this error

**Comment by NebelNidas** [comment]
@toqzd0 Can you upload/link the JAR file in question? If its license allows it
