### ISSUE TITLE
Unsupported class file major version 17263

### ISSUE THREAD

**Issue by FirephoenixX02** [FabricMC/Enigma#457]
How can i fix this error? Help is appreciated.
Error:
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Unsupported class file major version 17263
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3962)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4859)
	at cuchaz.enigma.classprovider.CachingClassProvider.get(CachingClassProvider.java:31)
	at cuchaz.enigma.analysis.index.JarIndex.indexJar(JarIndex.java:68)
	at cuchaz.enigma.Enigma.openJar(Enigma.java:65)
	at cuchaz.enigma.gui.GuiController.lambda$openJar$1(GuiController.java:105)
	at cuchaz.enigma.gui.dialog.ProgressDialog.lambda$runOffThread$1(ProgressDialog.java:97)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 17263
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
	at cuchaz.enigma.utils.AsmUtil.bytesToNode(AsmUtil.java:15)
	at cuchaz.enigma.classprovider.JarClassProvider.get(JarClassProvider.java:54)
	at cuchaz.enigma.classprovider.CombiningClassProvider.get(CombiningClassProvider.java:22)
	at cuchaz.enigma.classprovider.CachingClassProvider.lambda$get$0(CachingClassProvider.java:31)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4864)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	... 14 more

**Comment by modmuss50** [comment]
What are you trying to open? I expect a highly obfuscated jar? Enigma is only desiged to help rename lightly obfuscated jars, and will do nothing to sanitise highly obfucasted jars.

Maybe an option should be added to ingore these kinds of errors, but your most likely better of pre-processing the input to clean and remove invalid jar files before renaming with Enigma.

**Comment by FirephoenixX02** [comment]
> What are you trying to open? I expect a highly obfuscated jar? Enigma is only desiged to help rename lightly obfuscated jars, and will do nothing to sanitise highly obfucasted jars.
> 
> Maybe an option should be added to ingore these kinds of errors, but your most likely better of pre-processing the input to clean and remove invalid jar files before renaming with Enigma.
It's indeed a Highly obfuscated Jar. Do you know any other good deobfuscator for highly obfuscated/complex Jars?
