### ISSUE TITLE
Enigma randomly freezes

### ISSUE THREAD

**Issue by Advik-B** [FabricMC/Enigma#485]
<img width="1019" alt="Screenshot 2022-11-10 at 10 36 28 PM" src="https://user-images.githubusercontent.com/86160411/201160511-1a9616b5-b877-49b7-b337-758cdf22833c.png">

## Stack trace
```java
java.lang.OutOfMemoryError: Java heap space
	at java.desktop/java.awt.image.DataBufferInt.<init>(DataBufferInt.java:75)
	at java.desktop/java.awt.image.Raster.createPackedRaster(Raster.java:539)
	at java.desktop/java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1032)
	at java.desktop/java.awt.GraphicsConfiguration.createCompatibleImage(GraphicsConfiguration.java:184)
	at java.desktop/sun.awt.image.SunVolatileImage.getBackupImage(SunVolatileImage.java:251)
	at java.desktop/sun.awt.image.VolatileSurfaceManager.getBackupSurface(VolatileSurfaceManager.java:279)
	at java.desktop/sun.awt.image.VolatileSurfaceManager.restoreContents(VolatileSurfaceManager.java:310)
	at java.desktop/sun.java2d.SurfaceData.restoreContents(SurfaceData.java:285)
	at java.desktop/sun.java2d.opengl.CGLSurfaceData$CGLOffScreenSurfaceData.getReplacement(CGLSurfaceData.java:169)
```

## Other info

```yaml

OS: "MacOS Ventura"
Hardware: "Apple Silicon (M1 pro)"
Ram: "16GB"
Ram-allocated: "8GB"
java-version:  "17.0.1 2021-10-19 LTS"
```

### Command ran:
```
java -Xmx8G -jar enigma-swing-0.21.6+build.229-all.jar
```
---

Since I am a programmer myself, I do wonder why this happend, is 8GB not enough 🤔

**Comment by modmuss50** [comment]
Update engima, the version you are using is terribly out of date. Your missing this fix: https://github.com/FabricMC/Enigma/commit/9d7f57dadcd67342f8fa7b8618424f588ffcd28c
