### ISSUE TITLE
Every .Java File Fails To Export, with the error: java.nio.file.NoSuchFileException

### ISSUE THREAD

**Issue by EricKrouss** [FabricMC/Enigma#487]
Getting this error for EVERY FILE when attempting to extract Minecraft 1.19's source code
It'll go through the extracting process but nothing will show in the decided folder

java.nio.file.NoSuchFileException: C:\Enigma\Minecraft Source\Minecraft Source\net\minecraft\world\level\biome\TheEndBiomeSource.java
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:228)
        at java.base/java.nio.file.Files.newBufferedWriter(Files.java:3009)
        at java.base/java.nio.file.Files.newBufferedWriter(Files.java:3057)
        at cuchaz.enigma.EnigmaProject$ClassSource.writeTo(EnigmaProject.java:336)
        at cuchaz.enigma.gui.GuiController.lambda$exportSource$6(GuiController.java:269)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by GoldenMine0502** [comment]
https://github.com/FabricMC/Enigma/pull/494

**Comment by NebelNidas** [comment]
Fixed via https://github.com/FabricMC/Enigma/commit/537ecc84ca0e2119673301aa96176675504042e1.
