### ISSUE TITLE
Enigma crashes when trying to open a JAR file

### ISSUE THREAD

**Issue by Bettlee** [FabricMC/Enigma#493]
java.lang.Error: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Unsupported class file major version 61
	at cuchaz.enigma.gui.dialog.ProgressDialog.lambda$runOffThread$0(ProgressDialog.java:82)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Unsupported class file major version 61
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4873)
	at cuchaz.enigma.classprovider.CachingClassProvider.get(CachingClassProvider.java:31)
	at cuchaz.enigma.analysis.index.JarIndex.indexJar(JarIndex.java:70)
	at cuchaz.enigma.Enigma.openJar(Enigma.java:65)
	at cuchaz.enigma.gui.GuiController.lambda$openJar$0(GuiController.java:100)
	at cuchaz.enigma.gui.dialog.ProgressDialog.lambda$runOffThread$0(ProgressDialog.java:78)
	... 1 more
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 61
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:196)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
	at cuchaz.enigma.utils.AsmUtil.bytesToNode(AsmUtil.java:15)
	at cuchaz.enigma.classprovider.JarClassProvider.get(JarClassProvider.java:54)
	at cuchaz.enigma.classprovider.CombiningClassProvider.get(CombiningClassProvider.java:22)
	at cuchaz.enigma.classprovider.CachingClassProvider.lambda$get$0(CachingClassProvider.java:31)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4878)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	... 8 more

**Comment by modmuss50** [comment]
What version of enigma are you using?

**Comment by Bettlee** [comment]
The current latest version. I searched through comments on an older YouTube video explaining how to deobfuscate a Minecraft JAR. Someone had mentioned that Enigma doesn't support 1.17.x and higher
