### ISSUE TITLE
Crash with 18w43c bok class

### ISSUE THREAD

**Issue by liach** [FabricMC/Enigma#65]
```
java.lang.IllegalArgumentException: don't use with generic types or templates: T
	at cuchaz.enigma.mapping.TypeDescriptor.<init>(TypeDescriptor.java:31)
	at cuchaz.enigma.mapping.TypeDescriptor.getArrayType(TypeDescriptor.java:167)
	at cuchaz.enigma.mapping.TypeDescriptor.containsType(TypeDescriptor.java:171)
	at cuchaz.enigma.mapping.TypeDescriptor.remap(TypeDescriptor.java:190)
	at cuchaz.enigma.mapping.DirectionalTranslator.getTranslatedTypeDesc(DirectionalTranslator.java:283)
	at cuchaz.enigma.mapping.DirectionalTranslator.getTranslatedClass(DirectionalTranslator.java:53)
	at cuchaz.enigma.mapping.DirectionalTranslator.getTranslatedField(DirectionalTranslator.java:126)
	at cuchaz.enigma.mapping.Translator.getTranslatedEntry(Translator.java:95)
	at cuchaz.enigma.Deobfuscator.obfuscateEntry(Deobfuscator.java:494)
	at cuchaz.enigma.Deobfuscator.getSourceIndex(Deobfuscator.java:242)
	at cuchaz.enigma.Deobfuscator.getSourceIndex(Deobfuscator.java:220)
	at cuchaz.enigma.gui.GuiController.lambda$deobfuscate$3(GuiController.java:327)
	at java.lang.Thread.run(Thread.java:748)
```

Unfortunately, I don't know enough about enigma to help.

**Comment by liach** [comment]
It is fixed as of the time I comment. The latest enigma can open bok in 18w43c correctly.

**Comment by gegy1000** [comment]
Accidentally fixing bugs is the best way to fix bugs 😄
