### ISSUE TITLE
Unexpected FIELD entry

### ISSUE THREAD

**Issue by darkhax** [FabricMC/Enigma#9]
After the latest updates I encounter the following error when loading the pomf mappings. It doesn't seem very useful, so if you need further debugging let me know. 
```
cuchaz.enigma.throwables.MappingParseException: Line 2: Unexpected FIELD entry here!
	at cuchaz.enigma.mapping.MappingsEnigmaReader.readFile(MappingsEnigmaReader.java:103)
	at cuchaz.enigma.mapping.MappingsEnigmaReader.readDirectory(MappingsEnigmaReader.java:36)
	at cuchaz.enigma.mapping.MappingsEnigmaReader.readDirectory(MappingsEnigmaReader.java:38)
	at cuchaz.enigma.mapping.MappingsEnigmaReader.read(MappingsEnigmaReader.java:21)
	at cuchaz.enigma.gui.GuiController.openEnigmaMappings(GuiController.java:65)
	at cuchaz.enigma.Main.main(Main.java:32)
```

**Comment by Thog** [comment]
Strange I don't have any problems with my local workspace, have you checked your untracked files?

**Comment by darkhax** [comment]
The issue cleared up after nuking my local version. Didn't have any untracked files before hand.
